### ISSUE TITLE
Data Transfer of Run1.2p DRP data products from IN2P3 to NERSC

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#43] opened 2018-05-14 16:27 UTC
As discussed at today's DM-DC2 meeting, we will coordinate the transfer of data from IN2P3 to NERSC.  This issue will capture the list of files to transfer and the destination directory.

At NERSC: /global/projecta/projectdirs/lsst/global/in2p3 
I would recommend setting up a new subdirectory Run1.2p

**Comment by heather999** [comment] 2018-05-14 17:13
On Slack Simon notes the validateDrp inputs:
_calexps and src files. It can use jointcal outputs if available._
https://lsstc.slack.com/archives/C978LTJGN/p1526317672000458

**Comment by heather999** [comment] 2018-05-16 22:30
We should also keep an eye on https://github.com/LSSTDESC/DC2_Repo/issues/52

**Comment by wmwv** [comment] 2018-06-04 15:49
Things to transfer from IN2P3 `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_18/data` to NERSC:
```
input/_mapper
input/config
input/registry.sqlite3
input/ref_cats
output/calexp
output/config
output/deepCoadd
output/processEimage_metadata
output/schema
```

* Notes on filepaths:  
 - The `registry.sqlite3` file does not contain file paths.  It merely contains the information necessary to construct the filename _within_ a repository:
```
id|visit|channel|snap|sensor|ccd|raft|filter|taiObs|expTime
1|221612|0,7|0|0,0|0,0|2,3|g|2022-10-27T04:48:16.827199744|30.0
2|221612|1,2|0|1,0|1,0|1,2|g|2022-10-27T04:48:16.827199744|30.0
3|221612|0,1|0|1,0|1,0|1,3|g|2022-10-27T04:48:16.827199744|30.0
4|221612|0,4|0|1,0|1,0|1,3|g|2022-10-27T04:48:16.827199744|30.0
5|221612|0,5|0|1,0|1,0|0,1|g|2022-10-27T04:48:16.827199744|30.0
6|221612|1,4|0|2,0|2,0|0,2|g|2022-10-27T04:48:16.827199744|30.0
7|221612|1,4|0|2,0|2,0|1,3|g|2022-10-27T04:48:16.827199744|30.0
8|221612|1,0|0|0,2|0,2|2,2|g|2022-10-27T04:48:16.827199744|30.0
9|221612|1,0|0|0,1|0,1|0,3|g|2022-10-27T04:48:16.827199744|30.0
10|221612|0,5|0|0,2|0,2|1,3|g|2022-10-27T04:48:16.827199744|30.0
```

 - As @airnandez noted during the call, there is some path-dependence in the repository.  The filepath issue comes up when trying to read from a child "repo/rerun" to its parent.  Specifically, this relationship is in the `repositoryCfg.yaml` file.  E.g., there is a `output/repositoryCfg.yaml` file that contains a `root` entry that points to the directory on the IN2P3 machines:
```
/afs/in2p3.fr/home/w/wmwv/DC2/Run1.2p/data(0)>cat output/repositoryCfg.yaml
!RepositoryCfg_v1
_mapper: &id001 !!python/name:lsst.obs.lsstSim.lsstSimMapper.LsstSimMapper ''
_mapperArgs: {}
_parents:
- !RepositoryCfg_v1
  _mapper: *id001
  _mapperArgs: {}
  _parents: []
  _policy: null
  _root: /sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_18/data/input
  dirty: true
_policy: null
_root: null
dirty: true
```

This means is that trying to access a raw image from the `output` "rerun"/"repo" will fail.  But it was going to fail anyway because we didn't even transfer those images.

Within the `output` "repo/rerun", there is no lookup of the parent, so this shouldn't be an issue when we, e.g., read a coadd image and want to look up something about one of the calexps that went into it.

And, eventually, we could edit this file to update the `root` to point to the correct directory on NERSC.

**Comment by airnandez** [comment] 2018-06-05 09:53
## [2018-06-05] Run1.2p DRP: IN2P3 → NERSC data transfer campaign 

Summary of transfer campaign of data products of Run1.2p from IN2P3 to NERSC:

| Description  | Value |
| ------------: | :------------ |
| Location at CC-IN2P3 (source) | `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_18/data`|
| Location at NERSC (destination) | `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p` |
| Number of files transferred  | 98771  |
| Data volume transferred  | 659 GB  |

The list of files transferred is located at NERSC at:

`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/logs/2018-06-05-in2p3-to-nersc.txt`

The files transferred are the ones specified by @wmwv in the previous comment on this issue.

**NOTE:** no additional files present at IN2P3 under 

```
/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_18/data/output/src
```

were transferred to NERSC in this campaign (a first batch was already transferred in the transfer campaign on 2018-05-29) since the `src` subdirectory was not included in @wmwv's comment.

**Comment by wmwv** [comment] 2018-06-05 13:46
Oh, sorry!  That's because @wmwv was careless.  Yes, please do include `src`.

**Comment by airnandez** [comment] 2018-06-06 10:02
Thanks @wmwv. I now include files under `src` directory when transferring data from IN2P3 to NERSC. See below.

**Comment by airnandez** [comment] 2018-06-06 10:06
## [2018-06-06] Run1.2p DRP: IN2P3 → NERSC data transfer campaign 

Summary of transfer campaign of data products of Run1.2p from IN2P3 to NERSC:

| Description  | Value |
| ------------: | :------------ |
| Location at CC-IN2P3 (source) | `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_18/data`|
| Location at NERSC (destination) | `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p` |
| Number of files transferred  | 8655  |
| Data volume transferred  | 47 GB |

The list of files transferred is located at NERSC at:

`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/logs/2018-06-06-in2p3-to-nersc.txt`

**Comment by airnandez** [comment] 2018-06-08 16:36
@wmwv Done both items:

* copy of `output/repositoryCfg.yaml`
* move of `data/input` to `..`

This is the current status of the destination directory at NERSC:

```
$ tree -L 3 /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_18
/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_18
|-- data
|   `-- output
|       |-- calexp
|       |-- config
|       |-- deepCoadd
|       |-- processEimage_metadata
|       |-- repositoryCfg.yaml
|       |-- schema
|       `-- src
`-- input
    |-- _mapper
    |-- config
    |   `-- packages.pickle
    |-- ref_cats
    |   |-- cal_ref_cat
    |   `-- ref_cat_Run1.2p
    `-- registry.sqlite3

13 directories, 4 files
```

**Comment by wmwv** [comment] 2018-06-08 17:12
@airnandez  Ah, my apologies for the ambiguity.  I didn't mean move the actual directory `data/input`.

I meant change the one line in the `repositoryCfg.yaml` file to say 
```
 _root: ../input
```
instead of 
```
  _root: /sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_18/data/input
```

**Comment by airnandez** [comment] 2018-06-08 17:19
Corrected now:

```
$ tree -L 2 /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_18/data
/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_18/data
|-- input
|   |-- _mapper
|   |-- config
|   |-- ref_cats
|   `-- registry.sqlite3
`-- output
    |-- calexp
    |-- config
    |-- deepCoadd
    |-- processEimage_metadata
    |-- repositoryCfg.yaml
    |-- schema
    `-- src
```

```
$ cat /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_18/data/output/repositoryCfg.yaml
!RepositoryCfg_v1
_mapper: &id001 !!python/name:lsst.obs.lsstSim.lsstSimMapper.LsstSimMapper ''
_mapperArgs: {}
_parents:
- !RepositoryCfg_v1
  _mapper: *id001
  _mapperArgs: {}
  _parents: []
  _policy: null
  _root: ../input
  dirty: true
_policy: null
_root: null
dirty: true
```

**Comment by heather999** [comment] 2018-06-09 13:56
@airnandez, Jim mentioned we might also need `input/raw` transferred over. Those files are symlinks though, so we'll have to update where they are pointing at NERSC.  Any opinions @wmwv?

**Comment by jchiang87** [comment] 2018-06-09 14:43
To be precise, my statement was that I think we need the `raw` folder in order to run `constructFlat.py` to make sky flats.  Transferring that folder from IN2P3 may be helpful, but since the directory structure of that folder is straight-forward, we could just write a script to make the directory tree based on the contents of the registry file and our knowledge of where the phosim files live at NERSC.

**Comment by wmwv** [comment] 2018-06-09 18:50
Yes, to do processing at NERSC that uses the raw files, whether that's working on calibrations or redoing processEimage/Ccd tasks, you will need the raw files.

And, yes, @jchiang87 's suggestion is the correct one.  Just write a script to make the links in `input/raw` to the files that are already at NERSC.

**Comment by heather999** [comment] 2018-06-11 13:24
@airnandez Before I can add a raw subdirectory, first we need to adjust the permissions on /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p's subdirectories.  I would try running `setfacl -R -M /global/projecta/projectdirs/lsst/admin/ACL-all /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p` and see if that modifies the ACL settings such that the desc account again has write access to the area, while still preventing random users from making changes.  If that works, I might suggest you run that command for any new subdirectories that are added to this area in the future.

**Comment by airnandez** [comment] 2018-06-11 18:33
@heather999 I executed the command

```
setfacl -R -M /global/projecta/projectdirs/lsst/admin/ACL-all  /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p
```

which took about 10 minutes to complete. After executing this command, the ACLs are:

```
$ getfacl /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p
getfacl: Removing leading '/' from absolute path names
# file: global/projecta/projectdirs/lsst/global/in2p3/Run1.2p
# owner: fabioh
# group: lsst
# flags: -s-
user::rwx
user:desc:rwx
user:descdm:rwx
user:descpho:rwx
group::rwx
mask::rwx
other::---
default:user::rwx
default:user:desc:rwx
default:user:descdm:rwx
default:user:descpho:rwx
default:group::rwx
default:mask::rwx
default:other::---

$ getfacl /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_18 
getfacl: Removing leading '/' from absolute path names
# file: global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_18
# owner: fabioh
# group: lsst
# flags: -s-
user::rwx
user:desc:rwx
user:descdm:rwx
user:descpho:rwx
group::rwx
mask::rwx
other::---
default:user::rwx
default:user:desc:rwx
default:user:descdm:rwx
default:user:descpho:rwx
default:group::rwx
default:mask::rwx
default:other::---
```

Please let me know if this result is what you desired.

**Comment by heather999** [comment] 2018-06-12 03:09
@airnandez Yes that's closer, but I gave you the wrong ACL file.  Can you do it again: `setfacl -R -M /global/projecta/projectdirs/lsst/admin/ACL  /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p`

Sorry for the trouble, but I think this should fix it.

**Comment by airnandez** [comment] 2018-06-12 06:01
@heather999 Done:

```
$ time setfacl -R -M /global/projecta/projectdirs/lsst/admin/ACL /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p

real	12m53.857s
user	0m3.901s
sys	1m6.519s
```

And the ACLs are now:

```
$ getfacl /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p
getfacl: Removing leading '/' from absolute path names
# file: global/projecta/projectdirs/lsst/global/in2p3/Run1.2p
# owner: fabioh
# group: lsst
# flags: -s-
user::rwx
user:desc:rwx
user:descdm:rwx
user:descpho:rwx
group::r-x
mask::rwx
other::r-x
default:user::rwx
default:user:desc:rwx
default:user:descdm:rwx
default:user:descpho:rwx
default:group::r-x
default:mask::rwx
default:other::---


$ getfacl /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_18
getfacl: Removing leading '/' from absolute path names
# file: global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_18
# owner: fabioh
# group: lsst
# flags: -s-
user::rwx
user:desc:rwx
user:descdm:rwx
user:descpho:rwx
group::r-x
mask::rwx
other::r-x
default:user::rwx
default:user:desc:rwx
default:user:descdm:rwx
default:user:descpho:rwx
default:group::r-x
default:mask::rwx
default:other::---
```

**Comment by heather999** [comment] 2018-08-23 10:45
@airnandez @johannct I think more files need to come over, in particular /sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/coadd-all. Though Johann is reprocessing the coadds, so no need to update the transfer yet, but we should come back to this.
I would also like to confirm with those using the data (@jchiang87, @wmwv), do we have all that we need?

**Comment by wmwv** [comment] 2018-08-23 11:46
Once the forced-photometry catalog from the coadd Object positions are available (these will show up in `deepCoadd-results`) I can provide packaged GCR Object catalogs.

**Comment by heather999** [comment] 2018-08-24 22:42
Just dropping a link to Slack discussion: https://lsstc.slack.com/archives/C978LTJGN/p1535147216000100
/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/registry.sqlite3 was added today

**Comment by airnandez** [comment] 2018-08-31 08:53
## [2018-08-31] Run1.2p DRP: IN2P3 → NERSC data transfer campaign 

As requested by @johannct , this is the summary of a transfer campaign of data products of Run1.2p from IN2P3 to NERSC:

| Description  | Value |
| ------------: | :------------ |
| Location at CC-IN2P3 (source) | `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/w_2018_30/rerun/coadd-test3-u`|
| Location at NERSC (destination) | `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/w_2018_30/rerun/coadd-test3-u` |
| Number of files transferred  | 32320  |
| Data volume transferred  | 1.5 TB |

The list of files transferred is located at NERSC at:

`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/logs/2018-08-31-in2p3-to-nersc.txt`

**Comment by wmwv** [comment] 2018-08-31 12:12
Thanks, @airnandez .

As a trivial edit, the directory on NERSC is just
`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/coadd-test3-u`
instead of 
`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/w_2018_30/rerun/coadd-test3-u`

I.e., the `w_2018_30` isn't repeated.

**Comment by airnandez** [comment] 2018-08-31 12:18
Thanks @wmwv . Corrected above.

**Comment by rearmstr** [comment] 2018-08-31 13:07
We also need to change the `_root` path in  /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/080718/repositoryCfg.yaml to the corresponding filesystem on NERSC so that we can read it from the butler.

**Comment by airnandez** [comment] 2018-08-31 13:11
Done.

```
$ cat /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/080718/repositoryCfg.yaml
!RepositoryCfg_v1
_mapper: &id001 !!python/name:lsst.obs.lsstCam.lsstCamMapper.PhosimMapper ''
_mapperArgs: {}
_parents:
- !RepositoryCfg_v1
  _mapper: *id001
  _mapperArgs: {}
  _parents: []
  _policy: null
  _root: /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30
  dirty: true
_policy: null
_root: null
dirty: true
```

**Comment by airnandez** [comment] 2018-08-31 13:42
I would also prefer we use a relative path for the `_root` entry in the `repositoryCfg.yaml` file. 

However, the value of `_root` in the original `repositoryCfg.yaml`, which I kept and renamed to `repositoryCfg.yaml.ORI`, was the absolute path at IN2P3:

```
$ cat /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/080718/repositoryCfg.yaml.ORI
!RepositoryCfg_v1
_mapper: &id001 !!python/name:lsst.obs.lsstCam.lsstCamMapper.PhosimMapper ''
_mapperArgs: {}
_parents:
- !RepositoryCfg_v1
  _mapper: *id001
  _mapperArgs: {}
  _parents: []
  _policy: null
  _root: /sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30
  dirty: true
_policy: null
_root: null
dirty: true
```

Since at NERSC we replicate the same hierarchy existing at IN2P3 from a top directory, this is why I thought the butler was expecting the base directory. I can revert to the original file if you prefer, but I don't see how it would work.

**Comment by wmwv** [comment] 2018-08-31 14:02
The (current, Gen2) Butler expects the parent to be the input directory of the command.

E.g., when one runs
```
processCcd.py /sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30 --rerun 080718 ...
```

That creates a directory `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/080718` and stores the outputs of `processCcd.py` (calexp, src, etc.) in `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/080718`.  

Then `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/080718/repositoryCfg.yaml` points to its parent: `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30`

When one then runs
```
coaddDriver.py /sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/080718 --rerun coadd-test3-u
```

That creates the directory `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/coadd-test3-u` and `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/coadd-test3-u` points to its input repository, which is `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/080718`.

When you open `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/coadd-test3-u` with the Butler, it follows the chain of parents (`/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/080718`->``/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30`) to find the `registry.sqlite3` file.

At IN2P3`/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30` is the original repository into which the images were ingested.  This is the location of the `registry.sqlite3` file.  If we want a functional Butler at NERSC, we also need this original directory to contain at least a `registry.sqlite3` file and a `_mapper` file.  Note: if we never ask the Butler to retrieve them, then it's not actually important for this directory to contain a `raw` directory.

**Comment by wmwv** [comment] 2018-08-31 14:05
I would suggest that we use `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30` to be that directory.  Then copy the `_mapper` and `registry.sqlite3` files form `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/` to `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30`

Then the `registryCfg.yaml` for the `rerun/coadd-test3-u` should point to `../080718`.
And the `registryCfg.yaml` for the `rerun/080718` should point to `../..`.

(This is a slightly different choice than made for Run 1.1, where a specific `input` directory was created.  Either can work as long as the parent in the `repositoryCfg.yaml` points to the correct directory.)

**Comment by johannct** [comment] 2018-08-31 15:02
For what is worth :

**Comment by johannct** [comment] 2018-08-31 15:58
and I unfortunately confirm that my mapping is bugged. The coadds are still useful but some expected visits are missing so the depth is not what it should be. I will relaunch at CC with a code that reads the db that I have just finished to build

**Comment by airnandez** [comment] 2018-09-04 08:36
## [2018-09-04] Run1.2p DRP: IN2P3 → NERSC data transfer campaign 

As requested by @johannct, this is the summary of a transfer campaign of data products of Run1.2p from IN2P3 to NERSC:

| Description  | Value |
| ------------: | :------------ |
| Location at CC-IN2P3 (source) | `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/coadd-test5-u`|
| Location at NERSC (destination) | `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/coadd-test5-u` |
| Number of files transferred  | 67027  |
| Data volume transferred  | 3.5 TB |

The list of files transferred is located at NERSC at:

`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/logs/2018-09-04-in2p3-to-nersc.txt`

**Note**: the file `.../coadd-test5-u/repositoryCfg.yaml` was not modified since it already uses a relative path value for the `_parents` key.

**Comment by johannct** [comment] 2018-09-04 08:38
`coadd-test5-u` uses another code to map visits into tract/patches, and should solve the problem I raised above with my previous code.

**Comment by airnandez** [comment] 2018-10-02 07:42
## [2018-10-02] Run1.2p DRP: IN2P3 → NERSC data transfer campaign 

As requested by @johannct, this is the summary of a transfer campaign of data products of Run1.2p from IN2P3 to NERSC:

| Description  | Value |
| ------------: | :------------ |
| Location at CC-IN2P3 (sources) | `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/coadd-all2`, `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/210918`|
| Location at NERSC (destinations) | `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/coadd-all2`, `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/210918` |
| Number of files transferred  | 1,765,187  |
| Data volume transferred  | 80 TB |

The list of files transferred is located at NERSC at:

`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/logs/2018-10-02-in2p3-to-nersc.txt`

**NOTE:** the files `.../coadd-all2/repositoryCfg.yaml` and `.../210918/repositoryCfg.yaml` were not modified.

**Comment by wmwv** [comment] 2018-10-02 12:30
@airnandez Great!Is this the first full Run 1.2p reduction that the Data Access Task Force should try to serve.

**Comment by wmwv** [comment] 2018-10-02 12:30
@airnandez Great!  Is this the first full Run 1.2p reduction that the Data Access Task Force should try to serve?

@heather999 @boutigny @johannct

**Comment by wmwv** [comment] 2018-10-02 12:50
OK, thanks for the update.  We'll be ready to go as soon as the data are over.  Thanks for all of your work getting this through the processing!

**Comment by heather999** [comment] 2018-10-02 13:09
and just to be clear, this is certainly the first dataset to try to serve @wmwv, but be aware that the next reprocessing will include the fixed up calibrations.

**Comment by airnandez** [comment] 2018-10-05 07:59
## [2018-10-05] Run1.2p DRP: IN2P3 → NERSC data transfer campaign 

As requested by @johannct, this is the summary of a transfer campaign of data products of Run1.2p from IN2P3 to NERSC:

| Description  | Value |
| ------------: | :------------ |
| Location at CC-IN2P3 (sources) | `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/coadd-all2`|
| Location at NERSC (destinations) | `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/coadd-all2` |
| Number of files transferred  | 22,928  |
| Data volume transferred  | 12,7 GB |

The list of files transferred is located at NERSC at:

`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/logs/2018-10-05-in2p3-to-nersc.txt`

**NOTE:** at the source directory at IN2P3, there are files in two subdirectories named `deepCoadd-results` and `deepCoadd_results`, so that same namespace were reproduced at NERSC:

```
$ tree -L 1 /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/coadd-all2
/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/coadd-all2
|-- config
|-- config-save
|-- deepCoadd
|-- deepCoadd-results
|-- deepCoadd_results
|-- repositoryCfg.yaml
|-- schema
`-- scripts

7 directories, 1 file
```

For me, this looks as the symptom of a bug in the naming scheme implemented by the LSST stack for naming the outputs of some stage of the pipeline. If this subtlety in the naming is on purpose, it seems at least inconsistent to me.

**Comment by johannct** [comment] 2018-10-05 09:09
To be specific, `coadd-results` (for coaddDriver outputs) is defined in obs_base, while `coadd_results` is defined (for multibandDriver outputs) in `obs_lsstCam`. We do believe that this is a typo in obs_lsstCam, but would like to have confirmation from experts..... @rearmstr @RobertLuptonTheGood  ?

**Comment by rearmstr** [comment] 2018-10-08 15:39
This looks like a general change in how the data products are namee, moving a way from `-` to `_`.  We should confirm with @RobertLuptonTheGood.

**Comment by airnandez** [comment] 2018-10-18 12:07
## [2018-10-18] Run1.2p DRP: IN2P3 → NERSC data transfer campaign 

As requested by @johannct, this is the summary of a transfer campaign of data products of Run1.2p from IN2P3 to NERSC:

| Description  | Value |
| ------------: | :------------ |
| Location at CC-IN2P3 (sources) | `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/coadd-all2/deepCoadd_results`|
| Location at NERSC (destinations) | `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/coadd-all2/deepCoadd_results ` |
| Number of files transferred  | 7,125  |
| Data volume transferred  | 181.112 GB |

The list of files transferred is located at NERSC at:

`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/logs/2018-10-05-in2p3-to-nersc.txt`

**Comment by RobertLuptonTheGood** [comment] 2018-10-18 17:33
These are filenames, not template names, so the names don't actually matter if you always use the butler to retrieve them.
I would have no objection to your changing the `_` to `-` for consistency (I don't know why I changed them)

**Comment by airnandez** [comment] 2018-10-22 16:33
## [2018-10-22] Run1.2p DRP: IN2P3 → NERSC data transfer campaign 

As requested by @boutigny , this is the summary of a transfer campaign of data products of Run1.2p from IN2P3 to NERSC.

The purpose of this campaign was to make sure that the contents of the source directory at IN2P3 was entirely up-to-date at NERSC.

| Description  | Value |
| ------------: | :------------ |
| Location at CC-IN2P3 (source) | `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/coadd-all2`|
| Location at NERSC (destination) | `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/coadd-all2` |
| Number of files transferred  | 14,239  |
| Data volume transferred  | 1.3 TB |

The list of files transferred is located at NERSC at:

`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/logs/2018-10-22-in2p3-to-nersc.txt`

**Comment by airnandez** [comment] 2018-11-03 12:13
## [2018-11-03] Run1.2p DRP: IN2P3 → NERSC data transfer campaign 

As requested by @johannct, this is the summary of a transfer campaign of data products of Run1.2p from IN2P3 to NERSC.

The purpose of this campaign was to make sure that the contents recently generated at IN2P3 was entirely up-to-date at NERSC.

| Description  | Value |
| ------------: | :------------ |
| Location at CC-IN2P3 (source) | `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/coadd-all2`|
| Location at NERSC (destination) | `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/coadd-all2` |
| Number of files transferred  | 4,289  |
| Data volume transferred  | 262 GB |

The list of files transferred is located at NERSC at:

`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/logs/2018-11-03-in2p3-to-nersc.txt`

**Comment by airnandez** [comment] 2018-11-09 18:03
## [2018-11-09] Run1.2p DRP: IN2P3 → NERSC data transfer campaign 

This is the summary of a transfer campaign of data products of Run1.2p from IN2P3 to NERSC. The purpose of this campaign was to make sure that the contents generated at IN2P3 since the [last transfer campaign](https://github.com/LSSTDESC/ImageProcessingPipelines/issues/43#issuecomment-435583201) was entirely up-to-date at NERSC.

| Description  | Value |
| ------------: | :------------ |
| Location at CC-IN2P3 (source) | `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/coadd-all2`|
| Location at NERSC (destination) | `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/coadd-all2` |
| Number of files transferred  | 1,898  |
| Data volume transferred  | 83.3 GB |

The list of files transferred is located at NERSC at:

`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/logs/2018-11-09-in2p3-to-nersc.txt`

**Comment by airnandez** [comment] 2018-11-15 13:35
## [2018-11-15] Run1.2p DRP: IN2P3 → NERSC data transfer campaign 

This is the summary of a transfer campaign of data products of Run1.2p from IN2P3 to NERSC. The purpose of this campaign was to make sure that the contents generated at IN2P3 since the [last transfer campaign](https://github.com/LSSTDESC/ImageProcessingPipelines/issues/43#issuecomment-437443910) was entirely up-to-date at NERSC. Files present at NERSC that were no longer present at IN2P3 were removed.

| Description  | Value |
| ------------: | :------------ |
| Location at CC-IN2P3 (source) | `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_30/rerun/coadd-all2`|
| Location at NERSC (destination) | `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/w_2018_30/rerun/coadd-all2` |
| Number of files transferred  | 936  |
| Data volume transferred  | 4.6 GB |

The list of files transferred is located at NERSC at:

`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/logs/2018-11-15-in2p3-to-nersc.txt`

**Comment by johannct** [comment] 2018-11-15 13:44
this last transfer includes forced photometry for several patches of tract 5063. This run is supposedly complete. Please report any problem, while we are preparing the reprocessing (essentially with updated codebase and better calibration)

**Comment by airnandez** [comment] 2018-12-18 07:56
## [2018-12-18] Run1.2i DRP: IN2P3 → NERSC data transfer campaign 

This is the summary of a transfer campaign of data products of Run1.2i from IN2P3 to NERSC. It was requested by @johannct 

| Description  | Value |
| ------------: | :------------ |
| Location at CC-IN2P3 (sources) | `/sps/lsst/dataproducts/desc/DC2/Run1.2i/w_2018_39/rerun/281118`, `/sps/lsst/dataproducts/desc/DC2/Run1.2i/w_2018_39/rerun/coadd-v1`|
| Location at NERSC (destination) | `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2i/w_2018_39` |
| Number of files transferred  | 1,679,039  |
| Data volume transferred  | 70 TB |

The list of transferred files is located at NERSC at:

`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2i/logs/2018-12-18-in2p3-to-nersc.txt`

**Comment by heather999** [comment] 2018-12-18 13:55
@airnandez @johannct Thanks!  It would be nice to include the _mapper and registry.sqlite files too.  Bob had also asked about the reference catalog and CALIB files.  Is it possible to copy those over as well?  I have copies which should be identical, but it would probably be best to have the versions you actually used.

**Comment by johannct** [comment] 2018-12-18 15:08
For the record, the `input` `output` directories are one way to build the DM stack products. Currently we are moving away from this way and prefer to use the `rerun` tool. So we have a root file A, and one or more dirs under A/rerun. The path A and the dir names under rerun need to be provided when a transfer is planned. The rest should be standard. What was under `input` is now under A. What was under `output` is now in the rerun subdirs?

**Comment by airnandez** [comment] 2018-12-18 16:14
## [2018-12-18] Run1.2i DRP: IN2P3 → NERSC data transfer campaign 

This is the summary of a transfer campaign of data products of Run1.2i from IN2P3 to NERSC, to complete the [previous campaign on the same date](
https://github.com/LSSTDESC/ImageProcessingPipelines/issues/43#issuecomment-448129421) which was incomplete

| Description  | Value |
| ------------: | :------------ |
| Location at CC-IN2P3 (sources) | `/sps/lsst/dataproducts/desc/DC2/Run1.2i/w_2018_39/CALIB`, `/sps/lsst/dataproducts/desc/DC2/Run1.2i/w_2018_39/ref_cats`, `/sps/lsst/dataproducts/desc/DC2/Run1.2i/w_2018_39/_mapper`, `/sps/lsst/dataproducts/desc/DC2/Run1.2i/w_2018_39/registry.sqlite3`|
| Location at NERSC (destination) | `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2i/w_2018_39` |
| Number of files transferred  | 1,776  |
| Data volume transferred  | 112 GB |

The list of transferred files is located at NERSC at:

`/global/projecta/projectdirs/lsst/global/in2p3/Run1.2i/logs/2018-12-18b-in2p3-to-nersc.txt`

**NOTE:** some files end up with the executable bit set, even if they are not meant to be executables. This is the result of setting all the transferred files the reference ACL, which is located at `/global/projecta/projectdirs/lsst/admin/ACL`.

**Comment by johannct** [comment] 2019-12-02 14:16
completed.

**Closed by johannct** 2019-12-02 14:16 UTC
