### ISSUE TITLE
follow up on processEimage issues

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#32] opened 2018-03-02 16:50 UTC
Dominique B reported some problems with the images produced by processEimage and contacted the #desc-dm-eyeballs Slack channel:
https://lsstc.slack.com/files/U2K1GQADN/F9GF7HCQY/screenshot_from_2018-03-01_19-51-13.png
Simon offered to look at the differences between processEimage and processCcd.

**Comment by boutigny** [comment] 2018-03-05 13:41
The problem is that `processEimage.py` is  calling some methods with arguments which are different from those in `processCcd.py`. 
at https://github.com/LSSTDESC/obs_lsstSim/blob/master/python/lsst/obs/lsstSim/eimageIsr.py#L108 we have:
```
        isr.interpolateFromMask(
            maskedImage=mi,
            fwhm=self.config.interp_size,
            growFootprints=0,
            maskName='SAT',
        )```

in order to be compatible with `processCcd` we should have: `growFootprints=1`. Moreover the default value for `self.config.interp_size` is `0.5` while it should be `1`.

I will correct this file in order to make `growFootprints` a configurable parameter and to adjust the default.

Using parameters identical to `processCcd` the display of the saturated star that was exhibiting the problem is now ok as far as the bleeding trails are concerned. The 2 dark areas within the star footprint remain unexplained.
![screenshot from 2018-03-05 12-46-50](https://user-images.githubusercontent.com/5713323/36977966-3f37b744-2083-11e8-97f8-c6976053f79d.png)

**Comment by heather999** [comment] 2018-03-05 14:21
Thank you for the details @boutigny, I still have much to learn about the specifics of the processing. What I would like to do is reproduce your processing steps at NERSC, primarily just to see that it runs.  Is there a task in the SRS pipeline or script that you are using now?

**Comment by boutigny** [comment] 2018-03-05 14:29
At the moment, I am doing it step by step by hand and on 1 single visit. I can write down all the steps if you want.

**Comment by heather999** [comment] 2018-03-05 15:38
That would be very helpful :)

**Comment by boutigny** [comment] 2018-03-05 15:39
I have written down the instructions in https://github.com/LSSTDESC/ImageProcessingPipelines/wiki/Step-by-step-instructions-for-initial-cross-check-of-DM-DC2

**Comment by SimonKrughoff** [comment] 2018-03-05 20:07
@boutigny did you try turning up the number pixels you pad the saturated region by?

**Comment by SimonKrughoff** [comment] 2018-03-05 22:24
Sorry, reading more, you essentially did grow the footprint.  You mention making it configurable.  Does the high level config parameter not make it to the right place: `isr.growSaturationFootprintSize`?

I agree with Robert that we need to understand why we see this in sims, but not in other data.

**Comment by boutigny** [comment] 2018-03-05 22:58
The high level config parameter `isr.growSaturationFootprintSize` was not present in `processEimage.py` the value was hard coded to `0 ` in the isr.interpolateFromMask call (see: https://github.com/LSSTDESC/obs_lsstSim/blob/master/python/lsst/obs/lsstSim/eimageIsr.py#L108)

**Comment by nicolaschotard** [comment] 2018-03-08 09:22
@SimonKrughoff @jchiang87 Is there anyone against merging the branch Dominique create in `obs_lsstSIm` (https://github.com/LSSTDESC/obs_lsstSim/pull/5) to fix this specific problem with the master? If not, can someone with the write privilege do it?

**Comment by jchiang87** [comment] 2018-03-08 15:54
It's ok with me.  I just approved the PR.

**Comment by jchiang87** [comment] 2018-03-08 16:02
I'm going to close this now that [LSSTDESC/obs_lsstSim#5](https://github.com/LSSTDESC/obs_lsstSim/pull/5) has been merged.  Please make a new issue if there are other processEimage problems that arise.

**Closed by jchiang87** 2018-03-08 16:02 UTC
