### ISSUE TITLE
run_metacal is running on a 8 slot batch queue at CC-IN2P3 

### ISSUE THREAD

**Issue by boutigny** [LSSTDESC/ImageProcessingPipelines#128] opened 2019-09-24 14:55 UTC
Together with @johannct we discovered that `run_metacal` is configured to run on a 8 slot batch queue at CC-IN2P3 while the task is submitted as a serial one.
There are 2 possibilities: either `ngmix-deblended-bd.py`  and  `ngmix-deblended-mcalmax.py` can support the `-j ` option in which case it should be added or they don't support it and the SRS XML configuration file should be modified to select a single core queue (`${EXTRA_OPTIONS_0}`)
I am running some tests with metacal on CFHT data with -j option so I will be able to check if `-j` is useful.

**Comment by johannct** [comment] 2019-09-24 15:45
Pinging @esheldon as we also need to think about the best way to upgrade the code if needs be.

**Comment by esheldon** [comment] 2019-09-24 16:31
Yes, these are intrinsically serial, one core jobs.

**Comment by johannct** [comment] 2019-09-24 16:37
ok so I expect the -j 8 to not do anything special then. We need to do something about it, and open a dedicated ticket somewhere to upgrade these codes to MPI, no?

**Comment by boutigny** [comment] 2019-09-24 16:39
`-j n` will at least parallelize on the patches I guess. As we process 4 patches per job, I guess that `-j 4` would be useful

**Comment by esheldon** [comment] 2019-09-24 16:43
I see you assigned this to me.

However, I'm not sure what I can do.  The code runs on one core, it cannot be made to run intrinsically with MPI.

**Comment by johannct** [comment] 2019-09-24 16:44
oh just to be ready to close it and open a new issue to track upgrading effort to the code. It is single core even on the patches?

**Comment by esheldon** [comment] 2019-09-24 16:44
The expected way to run this would be one core per job and make sure you set `export OMP_NUM_THREADS=1` to prevent numpy from sometimes using more than one core for some operations

**Comment by esheldon** [comment] 2019-09-24 16:48
the code itself is not parallelized, meaning it does not run on multiple cores, does not use OPENMP, or mpi etc.

However, it can be run on subsets of a patch by using the `-c start_index` and `-c num_to_process`.

But I think it always writes the same file; this is I think by design from what I understand, a code can only write one filename, in fact it must be explicitly hard coded in the code.

**Comment by esheldon** [comment] 2019-09-24 16:50
we may need an expert to help how to make this work

**Comment by esheldon** [comment] 2019-09-24 16:56
Here is where the bd output file is hard coded when using deblended coadds

https://github.com/lsst-dm/meas_extensions_ngmix/blob/master/python/lsst/meas/extensions/ngmix/config.py#L307

Is there a way to over ride that?

**Comment by heather999** [comment] 2019-09-26 02:58
Given the conversation on Slack: https://lsstc.slack.com/archives/C978LTJGN/p1569344530018500
What is the conclusion? Are we in a position to update the code and templates ourselves to allow writing multiple files or do we stick with the single core queue for Run2.2i processing?

**Comment by johannct** [comment] 2019-09-26 07:52
no conclusion so far. The current code will be deprecated by DM, but not soon. The chunk idea seems a bit unnatural from the current state of the code. My hope was rather that we would be able to easily turn it into a PipelineTask or a pipe_driver task (even better)
The short term fix is certainly to change the submission so as not to waste resources.

**Comment by johannct** [comment] 2019-12-02 14:02
closing for now : the pipeline has been refactored so that metacal is distributed on the batch cluster per patch, see https://github.com/LSSTDESC/ImageProcessingPipelines/blob/7f262ef493da8c09ab35fb8773e346ee37359205/workflows/srs/pipe_setups/setup_metacal#L26

**Closed by johannct** 2019-12-02 14:02 UTC
