### ISSUE TITLE
Run2.2i DR6 bad coadd FITS files

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#158] opened 2020-08-18 18:21 UTC
There have been two instances of bad FITS file identified in the DR6 coadd output produced.

See Slack: 
[tract 4437 r-band patch 3,4](https://lsstc.slack.com/archives/C978LTJGN/p1597259548133000)
[tract 4437 y-band patch 3,1](https://lsstc.slack.com/archives/CB30ND9CG/p1597771354369300)

tract 4437 r-band 3,4 was rerun at CC and we confirmed that the resulting multiband output was identical.

**Comment by erykoff** [comment] 2020-08-18 20:26
Looks like tract 4437 z-band patch 5,2 is also bad.

**Comment by heather999** [comment] 2020-08-19 19:13
New copies of tract 4437 y-band patch 3,1 and z-band 5,2 were transferred over to NERSC: 
`run2.2i-coadd-wfd-dr6-v1-grizy/deepCoadd/y/4437/3,1.fits`
`run2.2i-coadd-wfd-dr6-v1-grizy/deepCoadd/z/4437/5,2.fits`
So we should be up to date with the fixed files

**Comment by erykoff** [comment] 2020-09-17 16:19
Another one: u-band 4437 3,2 is corrupt at NERSC.  I think there's also a bad one in u in 2735 but I'm having general disk access problems at the moment.

**Comment by erykoff** [comment] 2020-09-17 16:21
Oh wait, there is no 2735 in the u-band at nersc.  I guess that's at the edge?  Is this intentional?

**Comment by johannct** [comment] 2020-09-18 07:13
I confirm for 4437. @jchiang87  @katrinheitmann @heather999  How should we proceed? @fjaviersanchez  can you scrutinize 4437 in u band again?

Concerning 2735, there is only one non empty patch : 6,6, and indeed I do not see any u band coaddDriver output at CC.

**Comment by johannct** [comment] 2020-09-18 07:17
only one u-band visit interesected 2735 in patch 6,6 : visit=660397 detector=27 so coaddDriver bailed out.

**Comment by heather999** [comment] 2020-09-18 13:13
For 4437 3,2, can that be regenerated and we again confirm the follow-on multiband output is identical?  These corrupt files in the past have not indicated an issue with the multiband output, [same tract, patch 3,4 discussed on Slack](https://lsstc.slack.com/archives/C978LTJGN/p1597301712133900?thread_ts=1597259548.133000&cid=C978LTJGN) - at the end of that thread it looks like we were hoping Javi would take another look at dr6d, but I don't recall if that happened.

If the file can be regenerated and we confirm the resulting mutliband is unaffected, can we replace the corrupt file in DR6 WFD processing repo without having to worry about calling this v2?

**Comment by johannct** [comment] 2020-09-18 13:28
`If the file can be regenerated and we confirm the resulting mutliband is unaffected, can we replace the corrupt file in DR6 WFD processing repo without having to worry about calling this v2?`
In theory this is anathem, as we did publicize v1...

**Comment by heather999** [comment] 2020-09-18 14:15
Yes, I understand, that is why I want to know what effect this corrupt file has on what we released as DR6 WFD v1.  Has it impacted the multiband output or the object catalogs?  What would updating this corrupt file imply for the upstream data?
We could consider making a v2 - but I want to know what that will involve. New object catalog for 4437 and a new GCRCatalogs release?  
We could also decide one patch could be ignored and not bother with another release at this time.
If DR6 DDF is coming along and we believe there will be some upcoming DR6 release, we could incorporate this fixed patch at that time.

**Comment by erykoff** [comment] 2020-09-18 14:18
From past experience, it was only this one file that was corrupted, and all of the downstream stuff was okay.  So we should confirm this, but I think that just replacing the one file would not necessitate a "v2".

**Comment by johannct** [comment] 2020-09-22 13:56
@heather999 the file is ready at CC : `rerun/run2.2i-coadd-wfd-dr6-v1-u/deepCoadd/u/4437/3,2.fits`
All the other files, especially `rerun/run2.2i-coadd-wfd-dr6-v1-u/deepCoadd-results/u/4437/3,2/calexp-u-4437-3,2.fits` have been regenerated (it is very fast) and look identical to the former ones. @erykoff when you are satisfied you can close the issue.

**Comment by heather999** [comment] 2020-09-22 14:38
@erykoff I've moved aside the original 3,2.fits file and pulled over the reprocessed one and put it into `/global/cfs/cdirs/lsst/production/DC2_ImSim/Run2.2i/desc_dm_drp/v19.0.0-v1/rerun/run2.2i-coadd-wfd-dr6-v1-u/deepCoadd/u/4437/3,2.fits`  If it looks good, I'll just erase the old bad file and we can consider the DR6 WFD v1 repo updated.

**Comment by erykoff** [comment] 2020-09-22 16:06
I can confirm that the new file processed without any errors.  And I haven't found any other problems with coadd files in ugrizy in DC2 DR6(d) WFD, so I'm closing this issue.

**Closed by erykoff** 2020-09-22 16:06 UTC
Labels: 2.2i, production
